### ISSUE TITLE
Versjon 1

### ISSUE THREAD

**Issue by Barsnes** [felleslosninger/tlp-organization-chart#14]
# Hovudoppgåver
```[tasklist]
### Tasks
- [ ] https://github.com/felleslosninger/tlp-organization-chart/issues/17
- [ ] https://github.com/felleslosninger/tlp-organization-chart/issues/18
- [ ] https://github.com/felleslosninger/tlp-organization-chart/issues/78
- [ ] https://github.com/felleslosninger/tlp-organization-chart/issues/22
- [x] Release på npm (v0.1)
- [ ] https://github.com/felleslosninger/tlp-organization-chart/issues/32
- [ ] https://github.com/felleslosninger/tlp-organization-chart/issues/31
- [ ] https://github.com/felleslosninger/tlp-organization-chart/issues/80
- [ ] Ta i bruk ut mot folket (v1?)
```

Sjekk om JSDelivr kan tilby latest eller v1.x, for at brukarar får oppdateringa automatisk. https://www.jsdelivr.com/

## Andre ting som må bli gjort
- Skrive god dokumentsjon
  - README (root, pakke)
  - Bruk
  - Sette opp miljø
- Teste ut med visuell testing
  - Kan bli gjort etter første release
