### ISSUE TITLE
Gjer ferdig funksjonen (første utkast)

### ISSUE THREAD

**Issue by Barsnes** [felleslosninger/tlp-organization-chart#17]
```[tasklist]
### Tasks
- [x] "Spesial bokser" og strekar
- [x] Table of contents
- [x] testing og rettelser av aria-owns
```
