### ISSUE TITLE
Få på plass testar

### ISSUE THREAD

**Issue by Barsnes** [felleslosninger/tlp-organization-chart#78]
In #77 and #74 I added a testing environment that also runs in a workflow on github.
This is not for visual testing, but for testing the chart content, labels and functionality.

We need to add tests for these cases:
```[tasklist]
### Tasks
- [x] Roles
- [x] Ids
- [x] Correct amount of boxes, rows, etc.
- [x] Keyboard navigation and focus
- [x] Test prefix (css and ids)
```

**Comment by Barsnes** [comment]
Closing as resolved in #84
